### ISSUE TITLE
Use Site URL for frontend operations

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-msteams-sync#104]
At the moment, we are setting the server URL to `''` here

https://github.com/mattermost/mattermost-plugin-msteams-sync/blob/e95643e245dfbfae98e23db88e41c9a6cb61ada1/webapp/src/index.tsx#L16

when we should be using the Site URL as done in other plugins

https://github.com/mattermost/mattermost-plugin-zoom/blob/fcdab70c5da49c704ac701abb55ac5ee3c2489d7/webapp/src/index.js#L38

```ts
Client.setServerRoute(getServerRoute(store.getState()));
```

**Comment by gijsdb** [comment]
So you want that in index.tsx to be the following? 
`Client.setServerRoute(getServerRoute(store.getState()));`

Happy to take this issue.

**Comment by mickmister** [comment]
@gijsdb Yes sounds good to me :+1: Thank you!
