### ISSUE TITLE
Undo deleted messages from Teams not synced

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#131]
If a user deletes a message from Teams, it is also deleted from MM. But if the user undo the action taken(through the option already present in Teams), then the message is not presented back on MM channel.

![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/116162036/cbfcee63-945a-4951-9175-d63b5399c0df)

**Comment by jespino** [comment]
Yes, that is not supported yet. We have to think how to support that, but that is not an easy task because the mattermost API doesn't support "undelete". I think I can implement "undelete" in our side, but It is not trivial.
