### ISSUE TITLE
Handle lifecycle "subscriptionRemoved" event

### ISSUE THREAD

**Issue by manojmalik20** [mattermost/mattermost-plugin-msteams-sync#15]
The lifecycle "subscriptionRemoved" event from the MS Teams subscriptions are not handled. This is also a TODO comment in the code.

#### Reference
https://learn.microsoft.com/en-us/graph/webhooks-lifecycle#resources-that-support-lifecycle-notifications

#### Link
https://github.com/mattermost/mattermost-plugin-msteams-sync/blob/b9c6ab09301813f3102893f73b06930a94603095/server/api.go#L105

**Comment by jespino** [comment]
Actually, this is already done (I just did it), and now we need to handle the `lifecycle` missed (it is not mandatory, but depends on sync mechanism).

**Comment by jespino** [comment]
Repurposing this ticket for the "missed" event

**Comment by manojmalik20** [comment]
The resources that we're using don't support `missed` lifecycle notification event, so changing this issue to handle `subscriptionRemoved` event.

**Comment by ayusht2810** [comment]
fixed in PR https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/97. closing the issue
