### ISSUE TITLE
Complete Security Review

### ISSUE THREAD

**Issue by mkdbns** [mattermost/mattermost-plugin-msteams-sync#169]

**Comment by mkdbns** [comment]
Findings:

[MM-52101](https://mattermost.atlassian.net/browse/MM-52101)
[MM-51834](https://mattermost.atlassian.net/browse/MM-51834)

**Comment by esarafianou** [comment]
Findings:
[MM-53318](https://mattermost.atlassian.net/browse/MM-53318)
[MM-53285](https://mattermost.atlassian.net/browse/MM-53285)
