### ISSUE TITLE
Name of the attachments sent through MM is not synced

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#173]
If a user sends an attachment in any channel in MM, then the same attachment is shown on Teams with a different name.

**Steps to reproduce:-**
1. Send any attachment in any channel in MM.
2. Verify it on Teams.

![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/116162036/291028ad-b22f-4320-9445-04ab91e4ecd8)

![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/116162036/6911cbe0-9db5-4ecc-8f37-f26652ded862)

**Comment by ayusht2810** [comment]
Fixed in PR https://github.com/mattermost/mattermost-plugin-msteams-sync/pull/174. Closing the issue
