### ISSUE TITLE
Add unit tests for command.go file

### ISSUE THREAD

**Issue by Nityanand13** [mattermost/mattermost-plugin-msteams-sync#18]

**Comment by jespino** [comment]
The PR for this is merged, but the coverage of the command.go file is still less than 50%. Probably we should tests more cases there.

You can see the coverage executing `make coverage`, then running `go tool cover -html=server/coverage.txt -o coverage.html`, and then opening the `coverage.html` file.

**Comment by Nityanand13** [comment]
@jespino When you fix the issue [#21](https://github.com/mattermost/mattermost-plugin-msteams-sync/issues/21) then there will be changes in the executeConnectCommand and executeConnectBotCommand functions of the command.go.So will write the unit tests of mentioned function once the mentioned issue gets fixed.
