### ISSUE TITLE
Initiating DMs from MS Teams to Mattermost.

### ISSUE THREAD

**Issue by darias416** [mattermost/mattermost-plugin-msteams-sync#191]
Initiating a direct message to post within Mattermost is currently not supported. DMs from MS Teams can only be sent if the DM was first initiated from the Mattermost side.

**Comment by mkdbns** [comment]
@darias416 , per our discussion on MM, I don't think is an issue. Can you confirm?

**Comment by darias416** [comment]
@mkdbns Not an issue. Sorry for the delay here. This can be closed off or deleted.

**Comment by mkdbns** [comment]
Not an issue
