### ISSUE TITLE
Replies are being posted as new messages

### ISSUE THREAD

**Issue by manojmalik20** [mattermost/mattermost-plugin-msteams-sync#2]
When we post a reply on Mattermost, it is being posted as a new message on MS Teams.

#### Screenshots
In Mattermost
![image](https://user-images.githubusercontent.com/77336594/226598857-df9e0a29-8c39-41f0-b289-7e55d12e9a5b.png)

In MS Teams
![image](https://user-images.githubusercontent.com/77336594/226598921-e1ef1ea7-b80c-40d1-845b-9a3bf2fb1bd8.png)

**Comment by jespino** [comment]
This is not happening to me locally, can you put here the reproduction steps, or verify it with the last build?
