### ISSUE TITLE
Message not sent notifications

### ISSUE THREAD

**Issue by darias416** [mattermost/mattermost-plugin-msteams-sync#217]
Whenever a MM user, who has not connected their account, attempts to send a message to an MS Team user, they should receive a notification telling them their message was not sent because their account is not connected, and provide instructions on how to connect. 

One scenario to consider is if a group message is started in MM that includes MS Teams users, as well as MM users who have not connected their account, those "non-connected" MM users, when trying to add a message in the GM, should receive a notification telling them their message was not sent because their account is not connected, and provide instructions on how to connect.

**Comment by manojmalik20** [comment]
https://community.mattermost.com/core/pl/jw4pp3r4p7y85bkkepjy9ht8dw

**Comment by darias416** [comment]
@manojmalik20 thank you for the info. 

I enabled the bot and messages from MM users who are not connected do arrive in MS Teams as you mentioned. However, replies or new messages from the MS Teams side do not sync back to the channel in MM.

Also, it looks like whoever enables the bot, then turns into the bot. I'm assuming when authenticating the bot, the bot's credentials need to be used, correct? If so, we should explain that in the documentation.

**Comment by mkdbns** [comment]
@darias416 , note there is some information about create a user for the bot account in the docs. But it can be improved.

https://github.com/mattermost/mattermost-plugin-msteams-sync/blob/main/docs/azure_setup.md#step-2-create-a-user-account-to-act-as-a-bot

**Comment by manojmalik20** [comment]
@darias416 At first, I was not able to reproduce the issue of replies not working from Teams to MM because I was testing with a connected user and a non-connected user. The replies were working for a connected user. I have created a PR that resolves this issue and replies will also work for a non-connected user now.
