### ISSUE TITLE
Improve handling of dual notifications / unread messages

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-msteams-sync#300]
Suppose the following scenario:
- the MS Teams Connector is enabled
- User A has an account in Mattermost, MS Teams, and has connected their accounts
- User B has an account in Mattermost, MS Teams, and has connected their accounts

When User A sends User B a direct message, User B receives an unread mention in both platforms. 

If User B reads the message in Mattermost, the mention is not cleared in MS Teams, and vice versa.

This ticket is intended to start exploring ways to improve the handling of dual notifications / unread messages in the respective platforms.

**Comment by mkdbns** [comment]
Close as duplicate to Issue #287
