### ISSUE TITLE
Bug: Emoji reaction from Mattermost to MS Teams did not synchronize at 12:28pm PT on Oct 12, 2023

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-msteams-sync#350]
Due to the confidentiality of the details, see bug report below
https://docs.google.com/document/d/11f4qaAvH8-0hx8jQmRPq-PjYSWu3BdAVbLdl-07fMeo/edit

**Comment by lieut-data** [comment]
Looks likely to be a panic from `post` being `nil` on line 349 and having not checked the error there. We fetch i ton line 355

https://github.com/mattermost/mattermost-plugin-msteams-sync/blob/370fddc72cf8f4ec6644a9a217ed5234aff645d9/server/handlers/handlers.go#L349-L355
