### ISSUE TITLE
Bug: Mentions are not working properly from Teams to MM 

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#391]
## Steps to reproduce the bug

1. Go to linked channel in MS Teams.
2. Mention any desired user
3. Mention all the channel users with "@channelnameonTeams".
4. Go back to MM channel.

## Expected behaviour

The desired users and complete channel should get mentioned in MM channel also.

## Actual behaviour

The desired mentioned user is getting mentioned twice, and also the complete channel is not getting mentioned.

## Screenshots (optional)

![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/116162036/13a88518-0719-4b41-9d78-4c5f6a5b086c)

![image](https://github.com/mattermost/mattermost-plugin-msteams-sync/assets/116162036/998c19df-a36f-4749-85bc-f6f960773270)

**Comment by lieut-data** [comment]
MS Teams appears to have fixed this on their side.
