### ISSUE TITLE
Messages edited on Teams are not reflected on MM.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#53]
When any desired message is edited on Teams, the same is not reflected in MM channel.

**Steps to reproduce:-**
1. Enter any desired text message on Teams.
2. Verify it once on linked channel in MM.
3. Go back to the Teams channel and edit the same message.
4. Verify the same message on MM channel.

The message edited is not visible on MM channel.

![image](https://user-images.githubusercontent.com/116162036/229756622-403eec97-72a6-42ec-a0d2-845848226533.png)

![image](https://user-images.githubusercontent.com/116162036/229756708-d3a56585-9df6-4f8b-b5c6-774f8621844d.png)

**Also,** if user tries to edit a message on MM which was originally sent through Teams, it is not getting reflected on Teams and vice-versa.

**Comment by jespino** [comment]
Can you confirm that you hasn't linked the bot account that the one that you are writing the messages?

The bot account is expected to not be reused by other users, and all the messages are ignored if they come from the bot account.

**Comment by AayushChaudhary0001** [comment]
The bot account was not connected when this issue occurred.
