### ISSUE TITLE
No icon in the slash command suggestion and bot profile picture

### ISSUE THREAD

**Issue by manojmalik20** [mattermost/mattermost-plugin-msteams-sync#6]
In the suggestion menu of `/msteams-sync` slash command, there is no icon for the plugin. Similarly, there's no plugin specific profile picture for the `msteams` bot.

#### Screenshots
![image](https://user-images.githubusercontent.com/77336594/226601937-9cc13092-dbdc-4b3f-94ec-f1e42a0868ad.png)

Bot profile picture
![image](https://user-images.githubusercontent.com/77336594/226602320-09e4f41c-0a49-4197-91af-9e27d6629bf2.png)

**Comment by jespino** [comment]
This is already done
