### ISSUE TITLE
Weird error shown on linking the channel in DM's.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#63]
When the user tries to run the link slash command to link a channel, a weird error message is presented to the user of not being the channel admin, despite of him being the system admin.

![image](https://user-images.githubusercontent.com/116162036/230049271-f11239f0-74c1-4a7f-9033-b930fdbd8382.png)

![image](https://user-images.githubusercontent.com/116162036/230049505-8d0fe697-2f58-44aa-86be-d89e613e4d8c.png)

**Comment by jespino** [comment]
Good catch. I think the fix for this is detecting that you are trying to link a DM or GM and reporting to the user that is not allowed. @manojmalik20 do you want to take care of it?

**Comment by manojmalik20** [comment]
> Good catch. I think the fix for this is detecting that you are trying to link a DM or GM and reporting to the user that is not allowed. @manojmalik20 do you want to take care of it?

Yes @jespino. I'll assign it to myself.

**Comment by manojmalik20** [comment]
Fixed with #67
