### ISSUE TITLE
If the user does not exist in teams, then message added by the user in MM is missing.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#77]
If any user exists on MM, but is not a member of Teams, then the message delivered by that particular user on MM is not visible on Teams.

![Screenshot from 2023-04-13 20-49-19](https://user-images.githubusercontent.com/116162036/231807075-5c4c8164-053f-4f56-9ddc-9dfe80557f77.png)

![image](https://user-images.githubusercontent.com/116162036/231807220-9dfc2b7c-9940-4946-9e8a-fc77869ce9cb.png)

**Comment by mkdbns** [comment]
@AayushChaudhary0001 , i'm not sure I understand the specifics of this issue. Can you provide a bit more detail?

**Comment by AayushChaudhary0001** [comment]
@mkdbns It denoted that if a particular user(john.doe) in this case is a member of MM channel, but does not exist on Teams, then if that user(John.Doe) adds any message on MM channel, then that particular message is not visible on Teams.

**Comment by ayusht2810** [comment]
similar to issue #66 . We can use a bot account to post the message on teams.
