### ISSUE TITLE
Even after regenrating the webhook secret in plugin setting in MM, still the MM channel is in sync with the Teams.

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#89]
If the user regenerates the webhook secret after connecting the user and linking the channel, the linked channel in MM is still found in Sync with Teams. All the messages delivered on MM are visible on Teams and vice versa.
Instead, the expected behaviour should be that all the channels linked should get unlinked after regenerating the webhook secret.

**Comment by manojmalik20** [comment]
In the latest pull, this issue was not reproducible always. This was a bit flaky behaviour, so I changed the way the configuration values are being used and that resolved the issue.

**Comment by manojmalik20** [comment]
There's a change in the expected behavior. When a webhook secret is changed, the subscriptions still keep working and they are also updated on MS Graph with the latest updated webhook secret.
