### ISSUE TITLE
Not able to find which channel of MM is connected to the desired channel of Teams

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-msteams-sync#96]
If any desired channel of Teams is connected to a particular channel in MM, and the user tries to link other channel of MM to the same channel in Teams, then the user is not able to verify through the message received that which channel on MM is connected to the channel in Teams.

**Steps to reproduce:-**
1. Link any desired channel of MM to any particular channel in Teams.
2. Link any other channel of MM to the same channel in Teams as earlier.

The user is presented a message that the link already exists.
Through this message, it is not possible for the user to check which channel of MM is actually linked to the Teams channel. There should be a possible way at-least for the system admin on MM to find which channel is linked to the Teams channel.

**Comment by mkdbns** [comment]
If this is quick, this could be a High. Otherwise, we can move down to medium.

**Comment by manojmalik20** [comment]
For the slash command, table display approach, we are thinking of showing 100 or 200 records max for version 1. There could be thousands of channels potentially but for now, there doesn't exist a UI for connecting them and we think that there will not exist so many links without the UI. So for version 1, we are not introducing any pagination here and we can add that if there's a need in the future. What do you think @jespino?

**Comment by jespino** [comment]
That sounds like a good compromise to me. We can add pagination later easily, and also we are going to develop a better interface for that sooner than later.
